using System;
using System.Collections.Generic;
using HarmonyLib;
using UnityEngine;
using ValheimOne.Configuration;

namespace ValheimOne.Modules;

public sealed class ItemDropMultiplierModule : IFeatureModule
{
    private static ItemDropMultiplierModule? _active;

    private readonly FeatureDefinition _feature;
    private readonly ConfigEntryPercent _destructibleDrops;
    private readonly ConfigEntryPercent _creatureLoot;
    private readonly ConfigEntryPercent _pickableYields;

    public ItemDropMultiplierModule(FeatureRegistry registry)
    {
        _feature = registry.Register(Name, Section, Classification);
        _destructibleDrops = _feature.Percent(
            "DestructibleDrops",
            0f,
            "Drops from trees, rocks, and resource nodes that use a drop table.");
        _creatureLoot = _feature.Percent(
            "CreatureLoot",
            0f,
            "Quantity of loot generated by creatures.");
        _pickableYields = _feature.Percent(
            "PickableYields",
            0f,
            "Yield from pickable world objects such as berries and mushrooms.");
    }

    public string Name => "Item drop multiplier";

    public string Section => "Drops";

    public bool IsEnabled => _feature.Enabled.Value;

    public FeatureClassification Classification => FeatureClassification.ServerAuthoritative;

    public void ApplyPatches(Harmony harmony)
    {
        _active = this;

        var getDropList = AccessTools.Method(
            typeof(DropTable),
            nameof(DropTable.GetDropList),
            Type.EmptyTypes)
            ?? throw new MissingMethodException(nameof(DropTable), nameof(DropTable.GetDropList));
        harmony.Patch(
            getDropList,
            postfix: new HarmonyMethod(
                typeof(ItemDropMultiplierModule),
                nameof(GetDropListPostfix)));

        var getDropListItems = AccessTools.Method(
            typeof(DropTable),
            nameof(DropTable.GetDropListItems),
            Type.EmptyTypes)
            ?? throw new MissingMethodException(
                nameof(DropTable),
                nameof(DropTable.GetDropListItems));
        harmony.Patch(
            getDropListItems,
            postfix: new HarmonyMethod(
                typeof(ItemDropMultiplierModule),
                nameof(GetDropListItemsPostfix)));

        var generateDropList = AccessTools.Method(
            typeof(CharacterDrop),
            nameof(CharacterDrop.GenerateDropList),
            Type.EmptyTypes)
            ?? throw new MissingMethodException(
                nameof(CharacterDrop),
                nameof(CharacterDrop.GenerateDropList));
        harmony.Patch(
            generateDropList,
            postfix: new HarmonyMethod(
                typeof(ItemDropMultiplierModule),
                nameof(GenerateDropListPostfix)));

        var rpcPick = AccessTools.Method(
            typeof(Pickable),
            nameof(Pickable.RPC_Pick),
            new[] { typeof(long), typeof(int) })
            ?? throw new MissingMethodException(nameof(Pickable), nameof(Pickable.RPC_Pick));
        harmony.Patch(
            rpcPick,
            prefix: new HarmonyMethod(
                typeof(ItemDropMultiplierModule),
                nameof(PickableRpcPickPrefix)),
            finalizer: new HarmonyMethod(
                typeof(ItemDropMultiplierModule),
                nameof(PickableRpcPickFinalizer)));

        var getStackSize = AccessTools.Method(
            typeof(PickableItem),
            nameof(PickableItem.GetStackSize),
            Type.EmptyTypes)
            ?? throw new MissingMethodException(
                nameof(PickableItem),
                nameof(PickableItem.GetStackSize));
        harmony.Patch(
            getStackSize,
            postfix: new HarmonyMethod(
                typeof(ItemDropMultiplierModule),
                nameof(GetStackSizePostfix)));
    }

    private static void GetDropListPostfix(List<GameObject> __result)
    {
        ItemDropMultiplierModule? active = _active;
        if (active == null || !active.IsEnabled)
        {
            return;
        }

        ScaleEntries(__result, active._destructibleDrops);
    }

    private static void GetDropListItemsPostfix(List<ItemDrop.ItemData> __result)
    {
        ItemDropMultiplierModule? active = _active;
        if (active == null || !active.IsEnabled)
        {
            return;
        }

        ScaleEntries(__result, active._destructibleDrops);
    }

    private static void GenerateDropListPostfix(
        List<KeyValuePair<GameObject, int>> __result)
    {
        ItemDropMultiplierModule? active = _active;
        if (active == null || !active.IsEnabled)
        {
            return;
        }

        if (__result == null || active._creatureLoot.Value == 0f)
        {
            return;
        }

        for (int index = 0; index < __result.Count; index++)
        {
            KeyValuePair<GameObject, int> drop = __result[index];
            int amount = active._creatureLoot.ApplyChance(drop.Value);
            if (amount != drop.Value)
            {
                __result[index] = new KeyValuePair<GameObject, int>(drop.Key, amount);
            }
        }
    }

    private static void PickableRpcPickPrefix(
        Pickable __instance,
        out PickableAmountState __state)
    {
        __state = default;

        ItemDropMultiplierModule? active = _active;
        if (active == null || !active.IsEnabled)
        {
            return;
        }

        if (active._pickableYields.Value == 0f)
        {
            return;
        }

        // RPC_Pick runs synchronously on the object's owner and reads m_amount while creating
        // drops. Scaling the field only for that call avoids permanently changing prefab state;
        // the finalizer restores it even when the original method throws.
        __state = new PickableAmountState(__instance.m_amount);
        __instance.m_amount = active._pickableYields.ApplyChance(__state.OriginalAmount);
    }

    private static Exception? PickableRpcPickFinalizer(
        Pickable __instance,
        PickableAmountState __state,
        Exception? __exception)
    {
        ItemDropMultiplierModule? active = _active;
        if (active == null || !active.IsEnabled)
        {
            return __exception;
        }

        if (__state.ShouldRestore)
        {
            __instance.m_amount = __state.OriginalAmount;
        }

        return __exception;
    }

    private static void GetStackSizePostfix(ref int __result)
    {
        ItemDropMultiplierModule? active = _active;
        if (active == null || !active.IsEnabled)
        {
            return;
        }

        if (active._pickableYields.Value == 0f)
        {
            return;
        }

        __result = active._pickableYields.ApplyChance(__result);
    }

    private static void ScaleEntries<T>(List<T> entries, ConfigEntryPercent modifier)
    {
        if (entries == null || entries.Count == 0 || modifier.Value == 0f)
        {
            return;
        }

        var scaledEntries = new List<T>(entries.Count);
        foreach (T entry in entries)
        {
            int amount = modifier.ApplyChance(1f);
            for (int copy = 0; copy < amount; copy++)
            {
                scaledEntries.Add(entry);
            }
        }

        entries.Clear();
        entries.AddRange(scaledEntries);
    }

    private readonly struct PickableAmountState
    {
        public PickableAmountState(int originalAmount)
        {
            OriginalAmount = originalAmount;
            ShouldRestore = true;
        }

        public int OriginalAmount { get; }

        public bool ShouldRestore { get; }
    }
}
