#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
LIVEMAP_DIR="$(cd -- "$SCRIPT_DIR/.." && pwd)"
OUTPUT="$LIVEMAP_DIR/Web/EmbeddedAssets.g.cs"

"$SCRIPT_DIR/build-embed-assets.py"

ASSET_NAMES=(
    "index.html"
    "embed.html"
    "icons.js"
    "app.js"
    "app.embed.js"
    "app.css"
    "app.embed.css"
    "leaflet.js"
    "leaflet.css"
    "icon-192.png"
    "icon-64.png"
    "favicon.ico"
    "metamorphous-v22-latin-regular.woff2"
    "averia-serif-libre-v19-latin-regular.woff2"
    "averia-serif-libre-v19-latin-italic.woff2"
    "averia-serif-libre-v19-latin-700.woff2"
    "averia-serif-libre-v19-latin-700italic.woff2"
    "OFL-Metamorphous.txt"
    "OFL-AveriaSerifLibre.txt"
)

ASSET_PATHS=(
    "$LIVEMAP_DIR/web/index.html"
    "$LIVEMAP_DIR/web/embed.html"
    "$LIVEMAP_DIR/web/icons.js"
    "$LIVEMAP_DIR/web/app.js"
    "$LIVEMAP_DIR/web/app.embed.js"
    "$LIVEMAP_DIR/web/app.css"
    "$LIVEMAP_DIR/web/app.embed.css"
    "$LIVEMAP_DIR/web/vendor/leaflet.js"
    "$LIVEMAP_DIR/web/vendor/leaflet.css"
    "$LIVEMAP_DIR/web/icon-192.png"
    "$LIVEMAP_DIR/web/icon-64.png"
    "$LIVEMAP_DIR/web/favicon.ico"
    "$LIVEMAP_DIR/web/vendor/fonts/metamorphous-v22-latin-regular.woff2"
    "$LIVEMAP_DIR/web/vendor/fonts/averia-serif-libre-v19-latin-regular.woff2"
    "$LIVEMAP_DIR/web/vendor/fonts/averia-serif-libre-v19-latin-italic.woff2"
    "$LIVEMAP_DIR/web/vendor/fonts/averia-serif-libre-v19-latin-700.woff2"
    "$LIVEMAP_DIR/web/vendor/fonts/averia-serif-libre-v19-latin-700italic.woff2"
    "$LIVEMAP_DIR/web/vendor/fonts/OFL-Metamorphous.txt"
    "$LIVEMAP_DIR/web/vendor/fonts/OFL-AveriaSerifLibre.txt"
)

for asset_path in "${ASSET_PATHS[@]}"; do
    if [[ ! -f "$asset_path" ]]; then
        echo "Missing web asset: $asset_path" >&2
        exit 1
    fi
done

temporary_output="$(mktemp "$OUTPUT.tmp.XXXXXX")"
cleanup() {
    rm -f -- "$temporary_output"
}
trap cleanup EXIT

{
    printf '%s\n' '// Generated by tools/pack-web.sh -- do not edit by hand.'
    printf '%s\n' 'using System;'
    printf '%s\n' 'using System.Collections.Generic;'
    printf '%s\n' 'using System.IO;'
    printf '%s\n' 'using System.IO.Compression;'
    printf '\n'
    printf '%s\n' 'namespace ValheimOne.LiveMap;'
    printf '\n'
    printf '%s\n' 'internal static class EmbeddedAssets'
    printf '%s\n' '{'
    printf '%s\n' '    private static readonly Dictionary<string, string> Payloads = new Dictionary<string, string>'
    printf '%s\n' '    {'

    for index in "${!ASSET_NAMES[@]}"; do
        asset_name="${ASSET_NAMES[$index]}"
        asset_path="${ASSET_PATHS[$index]}"
        payload="$(gzip -9 -n -c < "$asset_path" | base64 -w 0)"
        payload_length="${#payload}"
        offset=0

        printf '        ["%s"] =\n' "$asset_name"
        while (( offset < payload_length )); do
            chunk="${payload:offset:4000}"
            offset=$((offset + ${#chunk}))
            if (( offset < payload_length )); then
                printf '            "%s" +\n' "$chunk"
            else
                printf '            "%s",\n' "$chunk"
            fi
        done
    done

    printf '%s\n' '    };'
    printf '\n'
    printf '%s\n' '    private static readonly Dictionary<string, string> ETags = new Dictionary<string, string>'
    printf '%s\n' '    {'

    for index in "${!ASSET_NAMES[@]}"; do
        asset_name="${ASSET_NAMES[$index]}"
        asset_path="${ASSET_PATHS[$index]}"
        asset_hash="$(sha256sum "$asset_path" | cut -d ' ' -f 1)"
        printf '        ["%s"] = "\\"%s\\"",\n' "$asset_name" "$asset_hash"
    done

    printf '%s\n' '    };'
    printf '\n'
    printf '%s\n' '    private static readonly Dictionary<string, byte[]> Cache = new Dictionary<string, byte[]>();'
    printf '%s\n' '    private static readonly Dictionary<string, byte[]> GzipCache = new Dictionary<string, byte[]>();'
    printf '\n'
    printf '%s\n' '    public static byte[] Get(string name)'
    printf '%s\n' '    {'
    printf '%s\n' '        if (name == null)'
    printf '%s\n' '        {'
    printf '%s\n' '            throw new KeyNotFoundException("Unknown embedded asset: " + name);'
    printf '%s\n' '        }'
    printf '\n'
    printf '%s\n' '        lock (Cache)'
    printf '%s\n' '        {'
    printf '%s\n' '            if (Cache.TryGetValue(name, out byte[] cached))'
    printf '%s\n' '            {'
    printf '%s\n' '                return cached;'
    printf '%s\n' '            }'
    printf '\n'
    printf '%s\n' '            if (!Payloads.ContainsKey(name))'
    printf '%s\n' '            {'
    printf '%s\n' '                throw new KeyNotFoundException("Unknown embedded asset: " + name);'
    printf '%s\n' '            }'
    printf '\n'
    printf '%s\n' '            byte[] compressed = GetGzip(name);'
    printf '%s\n' '            using (var input = new MemoryStream(compressed, writable: false))'
    printf '%s\n' '            using (var gzip = new GZipStream(input, CompressionMode.Decompress))'
    printf '%s\n' '            using (var output = new MemoryStream())'
    printf '%s\n' '            {'
    printf '%s\n' '                gzip.CopyTo(output);'
    printf '%s\n' '                byte[] asset = output.ToArray();'
    printf '%s\n' '                Cache.Add(name, asset);'
    printf '%s\n' '                return asset;'
    printf '%s\n' '            }'
    printf '%s\n' '        }'
    printf '%s\n' '    }'
    printf '\n'
    printf '%s\n' '    public static byte[] GetGzip(string name)'
    printf '%s\n' '    {'
    printf '%s\n' '        if (name == null)'
    printf '%s\n' '        {'
    printf '%s\n' '            throw new KeyNotFoundException("Unknown embedded asset: " + name);'
    printf '%s\n' '        }'
    printf '\n'
    printf '%s\n' '        lock (GzipCache)'
    printf '%s\n' '        {'
    printf '%s\n' '            if (GzipCache.TryGetValue(name, out byte[] cached))'
    printf '%s\n' '            {'
    printf '%s\n' '                return cached;'
    printf '%s\n' '            }'
    printf '\n'
    printf '%s\n' '            if (!Payloads.TryGetValue(name, out string encoded))'
    printf '%s\n' '            {'
    printf '%s\n' '                throw new KeyNotFoundException("Unknown embedded asset: " + name);'
    printf '%s\n' '            }'
    printf '\n'
    printf '%s\n' '            byte[] compressed = Convert.FromBase64String(encoded);'
    printf '%s\n' '            GzipCache.Add(name, compressed);'
    printf '%s\n' '            return compressed;'
    printf '%s\n' '        }'
    printf '%s\n' '    }'
    printf '\n'
    printf '%s\n' '    public static string GetETag(string name)'
    printf '%s\n' '    {'
    printf '%s\n' '        if (name == null || !ETags.TryGetValue(name, out string etag))'
    printf '%s\n' '        {'
    printf '%s\n' '            throw new KeyNotFoundException("Unknown embedded asset: " + name);'
    printf '%s\n' '        }'
    printf '\n'
    printf '%s\n' '        return etag;'
    printf '%s\n' '    }'
    printf '%s\n' '}'
} > "$temporary_output"

mv -- "$temporary_output" "$OUTPUT"
trap - EXIT
