#!/usr/bin/env python3
"""Development-only generator for synthetic ValheimOne World Timelapse frames.

This tool is not used by the plugin or included in release packages. Point it only
at an isolated development/test timelapse directory; never use a production
server's data directory. It prints synthetic-data banners, writes a
README-DEMO-DATA.txt marker, embeds ``DEMO`` in every frame's season field, and
refuses to touch existing ``.vof`` files unless that marker is present.

The current web UI does not display the season field, so screenshots and videos
made from these frames must be visibly captioned as synthetic demo data.
"""

import argparse
import math
import pathlib
import random
import struct
import time
import zlib


MAGIC = b"VOTL"
FORMAT_VERSION = 1
# There are nine int32 fields after unixMs; the resulting fixed header is 50 bytes.
HEADER = struct.Struct("<4sHq" + "i" * 9)
FOG_BYTES = 32768
FOG_WIDTH = 512
FOG_CELL_SIZE = 48.0
WORLD_HALF_SPAN = 12288.0
MOVEMENT_WIDTH = 128
MOVEMENT_CELL_SIZE = 192.0
MAX_COMPRESSED = 4 * 1024 * 1024
MAX_DECOMPRESSED = 512 * 1024
MARKER_NAME = "README-DEMO-DATA.txt"
RANDOM_SEED = 0x564F544C
POPCOUNT = tuple(bin(value).count("1") for value in range(256))

BOSS_KEYS = (
    "defeated_eikthyr",
    "defeated_gdking",
    "defeated_bonemass",
    "defeated_dragon",
    "defeated_goblinking",
    "defeated_queen",
    "defeated_fader",
)

# x, z, final pieces, final structural radius, appearance fraction
BASE_SPECS = (
    (120.0, -80.0, 1200, 110.0, 0.00),
    (3250.0, -1850.0, 810, 82.0, 0.13),
    (-3920.0, 2460.0, 690, 72.0, 0.30),
    (5230.0, 3560.0, 950, 96.0, 0.46),
    (-6120.0, -3040.0, 540, 62.0, 0.62),
    (1460.0, 6480.0, 430, 50.0, 0.77),
)

# One portal by every settled base, two remote outposts, and four transfer points.
PORTAL_SPECS = (
    (170.0, -30.0, 0.25),
    (3300.0, -1810.0, 0.30),
    (80.0, -150.0, 0.36),
    (8050.0, 5200.0, 0.42),
    (-3880.0, 2510.0, 0.44),
    (5280.0, 3510.0, 0.50),
    (-8200.0, 950.0, 0.54),
    (5190.0, 3650.0, 0.62),
    (-3990.0, 2400.0, 0.72),
    (-6070.0, -2980.0, 0.72),
    (1510.0, 6430.0, 0.82),
    (-6170.0, -3100.0, 0.88),
)

BED_SPECS = tuple((x + 8.0, z - 6.0, min(0.95, fraction + 0.03))
                  for x, z, _pieces, _radius, fraction in BASE_SPECS)

# Wards are near the three largest bases.
WARD_SPECS = (
    (135.0, -92.0, 0.55),
    (5250.0, 3580.0, 0.72),
    (3270.0, -1870.0, 0.84),
)

# The expedition crosses settled sites but takes wide, visibly wandering detours.
ROUTE = (
    (0.0, 0.0),
    (1800.0, 900.0),
    (3250.0, -1850.0),
    (5600.0, -3600.0),
    (7600.0, -900.0),
    (8050.0, 5200.0),
    (5230.0, 3560.0),
    (2600.0, 5000.0),
    (1460.0, 6480.0),
    (-2300.0, 5600.0),
    (-3920.0, 2460.0),
    (-8200.0, 950.0),
    (-6500.0, -900.0),
    (-6120.0, -3040.0),
    (-2600.0, -5900.0),
    (1800.0, -6800.0),
    (5600.0, -5100.0),
    (7200.0, -1700.0),
)

MARKER_TEXT = """SYNTHETIC DEMO DATA

These .vof files are synthetic frames generated by tools/timelapse-demo-seed.py
for a ValheimOne World Timelapse UI demonstration. They are NOT real world
history. The current web UI does not display the in-band DEMO season marker, so
every screenshot or video made from these frames must be visibly captioned as
synthetic demo data. Never mix this directory with production history. Delete
the frames after recording the demonstration.
"""


def require(condition, message):
    if not condition:
        raise AssertionError(message)


def banner(stage, output_dir):
    print("\n" + "=" * 72)
    print("SYNTHETIC DEMO DATA - " + stage)
    print("Output: " + str(output_dir))
    print("=" * 72)


def noise01(x, y, salt):
    value = (x * 0x1F123BB5) ^ (y * 0x5F356495) ^ (salt * 0x6C8E9CF5)
    value &= 0xFFFFFFFF
    value ^= value >> 16
    value = (value * 0x7FEB352D) & 0xFFFFFFFF
    value ^= value >> 15
    value = (value * 0x846CA68B) & 0xFFFFFFFF
    value ^= value >> 16
    return value / 4294967295.0


def stamp_disc(fog_bits, world_x, world_z, radius, salt):
    grid_x = (world_x + WORLD_HALF_SPAN) / FOG_CELL_SIZE - 0.5
    grid_y = (WORLD_HALF_SPAN - world_z) / FOG_CELL_SIZE - 0.5
    reach = radius / FOG_CELL_SIZE + 2.0
    x0 = max(0, int(math.floor(grid_x - reach)))
    x1 = min(FOG_WIDTH - 1, int(math.ceil(grid_x + reach)))
    y0 = max(0, int(math.floor(grid_y - reach)))
    y1 = min(FOG_WIDTH - 1, int(math.ceil(grid_y + reach)))

    for y in range(y0, y1 + 1):
        dz = (y - grid_y) * FOG_CELL_SIZE
        for x in range(x0, x1 + 1):
            dx = (x - grid_x) * FOG_CELL_SIZE
            boundary = radius * (0.84 + 0.32 * noise01(x, y, salt))
            if dx * dx + dz * dz <= boundary * boundary:
                bit_index = y * FOG_WIDTH + x
                fog_bits[bit_index >> 3] |= 1 << (bit_index & 7)


def expedition_position(progress):
    progress = min(1.0, max(0.0, progress))
    scaled = progress * (len(ROUTE) - 1)
    segment = min(len(ROUTE) - 2, int(math.floor(scaled)))
    local = scaled - segment
    x0, z0 = ROUTE[segment]
    x1, z1 = ROUTE[segment + 1]
    dx = x1 - x0
    dz = z1 - z0
    length = math.hypot(dx, dz)
    direction = -1.0 if segment % 2 else 1.0
    bend_size = 260.0 + 170.0 * math.sin((segment + 1) * 1.71)
    bend = direction * math.sin(math.pi * local) * bend_size
    if length:
        perpendicular_x = -dz / length
        perpendicular_z = dx / length
    else:
        perpendicular_x = 0.0
        perpendicular_z = 0.0
    return (
        x0 + dx * local + perpendicular_x * bend,
        z0 + dz * local + perpendicular_z * bend,
    )


def frame_fraction(frame_index, frame_count):
    if frame_count <= 1:
        return 1.0
    return frame_index / (frame_count - 1)


def present_points(specs, progress):
    return [(x, z) for x, z, appearance in specs if progress >= appearance]


def active_bases(frame_index, frame_count):
    result = []
    last_frame = max(0, frame_count - 1)
    for x, z, final_pieces, final_radius, appearance_fraction in BASE_SPECS:
        appearance = int(round(appearance_fraction * last_frame))
        if frame_index < appearance:
            continue
        available_frames = max(1, last_frame - appearance)
        growth = min(1.0, (frame_index - appearance) / available_frames)
        pieces = int(round(25 + (final_pieces - 25) * growth))
        radius = 18.0 + (final_radius - 18.0) * growth
        result.append((x, z, radius, pieces, growth))
    return result


def movement_cells(frame_index, frame_count, progress, bases, expedition):
    rng = random.Random(RANDOM_SEED + frame_index * 1000003)
    target_count = 150 + int(round(350 * progress))
    populated = {}
    attempts = 0

    while len(populated) < target_count:
        attempts += 1
        require(attempts < target_count * 200, "could not populate movement cells")
        if rng.random() < 0.64:
            recent_progress = max(0.0, progress - rng.random() * min(progress, 0.09))
            center_x, center_z = expedition_position(recent_progress)
            spread = 3.0 + 4.0 * rng.random()
        else:
            base = bases[rng.randrange(len(bases))]
            center_x, center_z = base[0], base[1]
            spread = 2.0 + 3.5 * rng.random()

        cell_x = int((center_x + WORLD_HALF_SPAN) / MOVEMENT_CELL_SIZE)
        cell_z = int((WORLD_HALF_SPAN - center_z) / MOVEMENT_CELL_SIZE)
        cell_x = int(round(cell_x + rng.gauss(0.0, spread)))
        cell_z = int(round(cell_z + rng.gauss(0.0, spread)))
        if not (0 <= cell_x < MOVEMENT_WIDTH and 0 <= cell_z < MOVEMENT_WIDTH):
            continue
        index = cell_z * MOVEMENT_WIDTH + cell_x
        if index not in populated:
            populated[index] = rng.randint(1, 40)

    return sorted(populated.items())


def append_string(buffer, text):
    encoded = text.encode("utf-8")
    require(len(encoded) <= 256, "string exceeds 256-byte hard cap")
    buffer.extend(struct.pack("<i", len(encoded)))
    buffer.extend(encoded)


def build_payload(fog_bits, bases, portals, beds, wards, movement, boss_keys):
    raw = bytearray(fog_bits)

    raw.extend(struct.pack("<i", len(bases)))
    for x, z, radius, pieces, _growth in bases:
        raw.extend(struct.pack("<fffi", x, z, radius, pieces))

    for points in (portals, beds, wards):
        raw.extend(struct.pack("<i", len(points)))
        for x, z in points:
            raw.extend(struct.pack("<ff", x, z))

    raw.extend(struct.pack("<i", len(movement)))
    for cell_index, count in movement:
        raw.extend(struct.pack("<Hi", cell_index, count))

    raw.extend(struct.pack("<i", len(boss_keys)))
    for key in boss_keys:
        append_string(raw, key)
    append_string(raw, "DEMO")

    require(len(raw) < MAX_DECOMPRESSED, "decompressed payload reaches 512 KiB cap")
    compressor = zlib.compressobj(9, zlib.DEFLATED, -15)
    compressed = compressor.compress(bytes(raw)) + compressor.flush()
    require(len(compressed) <= MAX_COMPRESSED, "compressed payload exceeds 4 MiB cap")
    return compressed


def write_frames(output_dir, frame_count, hours_per_frame, end_unix_ms):
    # 72 frames at the 4-hour default cover 12 days, deliberately staying inside
    # the plugin's 14-day hourly retention window so none of the demo is thinned.
    step_ms = int(round(hours_per_frame * 60.0 * 60.0 * 1000.0))
    require(step_ms > 0, "--hours-per-frame must produce a positive millisecond step")
    first_unix_ms = end_unix_ms - (frame_count - 1) * step_ms
    fog_bits = bytearray(FOG_BYTES)
    stamp_disc(fog_bits, 0.0, 0.0, 520.0, 11)
    written = []

    for frame_index in range(frame_count):
        progress = frame_fraction(frame_index, frame_count)
        path_start = frame_index / frame_count
        path_end = (frame_index + 1) / frame_count
        path_steps = max(1, int(math.ceil(
            (path_end - path_start) * (len(ROUTE) - 1) * 26.0
        )))
        for substep in range(1, path_steps + 1):
            path_progress = path_start + (path_end - path_start) * substep / path_steps
            expedition_x, expedition_z = expedition_position(path_progress)
            trail_radius = (
                875.0
                + 210.0 * math.sin(path_progress * math.pi * 7.0) ** 2
                + 260.0 * path_progress
            )
            stamp_disc(
                fog_bits,
                expedition_x,
                expedition_z,
                trail_radius,
                1000 + int(path_progress * 100000.0),
            )

        bases = active_bases(frame_index, frame_count)
        for base_number, base in enumerate(bases):
            settlement_radius = 650.0 + base[4] * (1200.0 + 140.0 * (base_number % 3))
            stamp_disc(fog_bits, base[0], base[1], settlement_radius, 200 + base_number)

        portals = present_points(PORTAL_SPECS, progress)
        beds = present_points(BED_SPECS, progress)
        wards = present_points(WARD_SPECS, progress)
        expedition = expedition_position(path_end)
        movement = movement_cells(frame_index, frame_count, progress, bases, expedition)

        unlock_thresholds = (0.12, 0.35, 0.58, 0.80)
        unlocked = sum(1 for threshold in unlock_thresholds if progress >= threshold)
        boss_keys = BOSS_KEYS[:unlocked]
        boss_mask = (1 << unlocked) - 1
        explored_cells = sum(POPCOUNT[value] for value in fog_bits)
        world_day = 1 + frame_index * 3 + frame_index // 4
        payload = build_payload(
            fog_bits, bases, portals, beds, wards, movement, boss_keys
        )
        unix_ms = first_unix_ms + frame_index * step_ms
        header = HEADER.pack(
            MAGIC,
            FORMAT_VERSION,
            unix_ms,
            world_day,
            explored_cells,
            len(bases),
            len(portals),
            len(beds),
            len(wards),
            boss_mask,
            len(movement),
            len(payload),
        )
        require(len(header) == 50, "header is not exactly 50 bytes")
        destination = output_dir / (str(unix_ms) + ".vof")
        destination.write_bytes(header + payload)
        written.append(destination)

    return written


def read_i32(raw, offset):
    require(offset + 4 <= len(raw), "truncated int32")
    return struct.unpack_from("<i", raw, offset)[0], offset + 4


def verify_frame(path):
    data = path.read_bytes()
    require(len(data) >= HEADER.size, str(path) + ": truncated header")
    fields = HEADER.unpack_from(data, 0)
    require(fields[0] == MAGIC, str(path) + ": bad magic")
    require(fields[1] == FORMAT_VERSION, str(path) + ": bad format version")
    require(HEADER.pack(*fields) == data[:HEADER.size], str(path) + ": header round-trip failed")

    (
        _magic,
        _version,
        unix_ms,
        _world_day,
        explored_cells,
        header_base_count,
        header_portal_count,
        header_bed_count,
        header_ward_count,
        boss_mask,
        header_movement_count,
        payload_length,
    ) = fields
    payload = data[HEADER.size:]
    require(payload_length == len(payload), str(path) + ": payload length mismatch")
    require(payload_length <= MAX_COMPRESSED, str(path) + ": compressed payload exceeds cap")
    raw = zlib.decompress(payload, -15)
    require(len(raw) < MAX_DECOMPRESSED, str(path) + ": decompressed payload reaches cap")

    require(len(raw) >= FOG_BYTES, str(path) + ": truncated fog bits")
    fog_bits = raw[:FOG_BYTES]
    require(len(fog_bits) == FOG_BYTES, str(path) + ": fog length mismatch")
    require(
        sum(POPCOUNT[value] for value in fog_bits) == explored_cells,
        str(path) + ": explored cell count mismatch",
    )
    offset = FOG_BYTES

    base_count, offset = read_i32(raw, offset)
    require(base_count == header_base_count and 0 <= base_count <= 512,
            str(path) + ": base count mismatch or cap exceeded")
    require(offset + base_count * 16 <= len(raw), str(path) + ": truncated bases")
    offset += base_count * 16

    point_counts = []
    for label, expected in (
        ("portal", header_portal_count),
        ("bed", header_bed_count),
        ("ward", header_ward_count),
    ):
        count, offset = read_i32(raw, offset)
        require(count == expected and 0 <= count <= 4096,
                str(path) + ": " + label + " count mismatch or cap exceeded")
        require(offset + count * 8 <= len(raw), str(path) + ": truncated " + label + " points")
        offset += count * 8
        point_counts.append(count)

    movement_count, offset = read_i32(raw, offset)
    require(
        movement_count == header_movement_count and 0 <= movement_count <= 16384,
        str(path) + ": movement count mismatch or cap exceeded",
    )
    for _ in range(movement_count):
        require(offset + 6 <= len(raw), str(path) + ": truncated movement cell")
        cell_index, _count = struct.unpack_from("<Hi", raw, offset)
        require(cell_index < 16384, str(path) + ": movement cell index out of range")
        offset += 6

    boss_key_count, offset = read_i32(raw, offset)
    require(0 <= boss_key_count <= 64, str(path) + ": boss key cap exceeded")
    decoded_keys = []
    for _ in range(boss_key_count):
        byte_length, offset = read_i32(raw, offset)
        require(0 <= byte_length <= 256, str(path) + ": boss key string cap exceeded")
        require(offset + byte_length <= len(raw), str(path) + ": truncated boss key")
        decoded_keys.append(raw[offset:offset + byte_length].decode("utf-8"))
        offset += byte_length

    season_length, offset = read_i32(raw, offset)
    require(0 <= season_length <= 256, str(path) + ": season string cap exceeded")
    require(offset + season_length <= len(raw), str(path) + ": truncated season")
    season = raw[offset:offset + season_length].decode("utf-8")
    offset += season_length

    require(offset == len(raw), str(path) + ": trailing decompressed bytes")
    require(tuple(decoded_keys) == BOSS_KEYS[:boss_key_count], str(path) + ": boss key order mismatch")
    require(boss_mask == (1 << boss_key_count) - 1, str(path) + ": boss mask mismatch")
    require(season == "DEMO", str(path) + ": missing in-band DEMO marker")
    return unix_ms, explored_cells, len(data)


def verify_and_summarize(paths):
    verified = [verify_frame(path) for path in paths]
    require(verified, "no frames were written")
    sizes = sorted(item[2] for item in verified)
    middle = len(sizes) // 2
    if len(sizes) % 2:
        median = float(sizes[middle])
    else:
        median = (sizes[middle - 1] + sizes[middle]) / 2.0
    first = verified[0]
    last = verified[-1]
    first_percent = first[1] * 100.0 / (FOG_WIDTH * FOG_WIDTH)
    last_percent = last[1] * 100.0 / (FOG_WIDTH * FOG_WIDTH)
    require(25.0 <= last_percent <= 35.0,
            "final explored percentage is outside the requested 25-35% range")

    print("\nSelf-verification summary")
    print("  Frame count:                 " + str(len(verified)))
    print("  Total bytes:                 " + str(sum(sizes)))
    print("  Frame bytes min/median/max:  {}/{:.1f}/{}".format(sizes[0], median, sizes[-1]))
    print("  First timestamp:             {} ({:.2f}% explored)".format(first[0], first_percent))
    print("  Last timestamp:              {} ({:.2f}% explored)".format(last[0], last_percent))


def parse_args():
    parser = argparse.ArgumentParser(
        description="Generate synthetic ValheimOne World Timelapse demo frames."
    )
    parser.add_argument("--output", required=True, help="directory for synthetic .vof frames")
    parser.add_argument("--frames", type=int, default=72)
    parser.add_argument("--hours-per-frame", type=float, default=4.0)
    parser.add_argument("--end-unix-ms", type=int, default=None)
    parser.add_argument("--clean", action="store_true")
    return parser.parse_args()


def main():
    args = parse_args()
    output_dir = pathlib.Path(args.output).expanduser().resolve()
    banner("START", output_dir)
    require(args.frames > 0, "--frames must be positive")
    require(math.isfinite(args.hours_per_frame) and args.hours_per_frame > 0.0,
            "--hours-per-frame must be a positive finite number")
    output_dir.mkdir(parents=True, exist_ok=True)
    marker_path = output_dir / MARKER_NAME
    existing_frames = sorted(output_dir.glob("*.vof"))

    # This guard deliberately runs before cleaning: unlabelled frames may be real history.
    if existing_frames and not marker_path.is_file():
        print("ERROR: refusing to touch unlabelled .vof files in " + str(output_dir))
        print("They may be real captured history; " + MARKER_NAME + " is missing.")
        raise SystemExit(2)

    if args.clean:
        for frame_path in existing_frames:
            frame_path.unlink()
        if marker_path.exists():
            marker_path.unlink()

    marker_path.write_text(MARKER_TEXT, encoding="utf-8")
    end_unix_ms = args.end_unix_ms
    if end_unix_ms is None:
        end_unix_ms = int(time.time() * 1000.0)
    paths = write_frames(
        output_dir,
        args.frames,
        args.hours_per_frame,
        end_unix_ms,
    )
    verify_and_summarize(paths)
    banner("FINISH", output_dir)


if __name__ == "__main__":
    main()
